In [36]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.datasets import load_wine

import warnings
warnings.filterwarnings('ignore')


In [37]:
# Loading dataset
wine = load_wine()
x = wine.data
y = wine.target.reshape(-1, 1)  # Reshape for one-hot encoding
print(x)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [38]:
# Normalization 
scaler = StandardScaler()
x = scaler.fit_transform(x)

# one-hot encoding
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)


In [39]:
# training and testing 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [40]:
model = Sequential([
    Dense(10, input_shape=(13,), activation='relu'),  
    Dense(3, activation='softmax') 
])
# Hidden layer-10 neurons and ReLU is using activation
 # Output layer- 3, softmax activation


In [41]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [42]:
model.fit(x_train, y_train, epochs=10, batch_size=5, validation_split=0.2)


Epoch 1/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.3971 - loss: 1.0133 - val_accuracy: 0.7241 - val_loss: 0.8739
Epoch 2/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5426 - loss: 0.9499 - val_accuracy: 0.8276 - val_loss: 0.7719
Epoch 3/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7029 - loss: 0.8274 - val_accuracy: 0.8621 - val_loss: 0.6898
Epoch 4/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8154 - loss: 0.7590 - val_accuracy: 0.9310 - val_loss: 0.6085
Epoch 5/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8772 - loss: 0.6790 - val_accuracy: 0.9310 - val_loss: 0.5426
Epoch 6/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9089 - loss: 0.6293 - val_accuracy: 0.9310 - val_loss: 0.4805
Epoch 7/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9310 - loss: 0.5249 - val_accuracy: 0.9655 - val_loss: 0.4216
Epoch 8/10
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9440 - loss: 0.5052 - val_accuracy: 1.0000 - val_loss

In [43]:
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print('\n accuracy:', test_acc)


2/2 - 0s - 24ms/step - accuracy: 0.8889 - loss: 0.3474

 accuracy: 0.8888888955116272
